<?php

namespace proyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlergiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlergiasRepository extends EntityRepository
{
}
