<?php

namespace proyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactoEmergenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoEmergenciaRepository extends EntityRepository
{
}
