<?php

namespace proyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NumerosPacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumerosPacienteRepository extends EntityRepository
{
	
}
