<?php

namespace proyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecetasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetasRepository extends EntityRepository
{
}
