<?php

namespace Zenva\WorkoutBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkaoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkaoutRepository extends EntityRepository
{
}
